### ISSUE TITLE
Repo out of sync?

### ISSUE THREAD

**Issue by brettwooldridge** [intrbiz/SNMP-IB#1]
@intrbiz Hi Chris, I noticed that the [``pom.xml``](https://github.com/intrbiz/SNMP-IB/blob/master/pom.xml#L7) in the repo shows ``1.0.0-SNAPSHOT``, but there exists a ``1.0.1`` release artifact in [your repository](http://nexus.intrbiz.net/nexus/content/repositories/releases/com/intrbiz/snmp-ib/snmp-ib/1.0.1/).  Are there changes elsewhere that are not present in this repo?

**Comment by brettwooldridge** [comment]
@intrbiz Ping.

**Comment by intrbiz** [comment]
Hi, the release branch has the 1.0.1 release version.  At the time master was my development branch, with a release branch for releases.
